### 获取用户列表
GET {{baseUrl}}/users
Accept: application/json
Authorization: {{token}}

### 按照ID获取用户
GET {{baseUrl}}/users/1
Accept: application/json
Authorization: {{token}}

### 添加用户
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: {{token}}

{
  "username": "wangwu",
  "password": "123456",
  "email": "wangwu@qq.com",
  "phone": "13200000002",
  "gender": "1",
  "create_by": "admin",
  "remark": "测试",
  "role_id": 2
}

### 删除用户
DELETE {{baseUrl}}/users/3
Accept: application/json
Authorization: {{token}}
