### 注册用户
POST {{baseUrl}}/api/register
Content-Type: application/json

{
  "username": "lisi",
  "password": "123456",
  "email": "lisi@163.com",
  "phone": "13200000001",
  "gender": "1"
}

### 账号登录
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "username": "lisi",
  "password": "123456"
}

### 手机登录
POST {{baseUrl}}/api/loginphone
Content-Type: application/json

{
  "phone": "17374000851",
  "password": "123456"
}
