### 注册用户
POST {{baseUrl}}/api/register
Content-Type: application/json

{
  "username": "lisi",
  "password": "123456",
  "email": "lisi@qq.com",
  "phone": "13200000001",
  "gender": "1"
}

### 账号登录
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "username": "lisi",
  "password": "123456"
}

### 手机登录
POST {{baseUrl}}/api/loginphone
Content-Type: application/json

{
  "phone": "17374000851",
  "password": "123456"
}

### 获取验证码
POST {{baseUrl}}/api/getcheckcode
Content-Type: application/json

{
  "email": "lisi@qq.com"
}

### 重置密码
PUT {{baseUrl}}/api/resetpassword
Content-Type: application/json

{
  "checkCode": "rdeS",
  "newPassword": "123456",
  "affirmPassword": "123456"
}
